import json
from pathlib import Path

ROOT = Path("/Users/sophiasun/Desktop/2cool4school/2026/aquarius")
LOG = ROOT / "data/regions_curated/search_log.jsonl"

meta, srcq = {}, {}
for line in LOG.open():
    d = json.loads(line)
    for h in d["hits"]:
        vid = h["video_id"]
        meta.setdefault(vid, h)
        srcq.setdefault((d["region"], vid), d["query"])
        srcq.setdefault(("*", vid), d["query"])

# (vid, song, area, genre, perf, note)
Y = "原生态"; M = "民族唱法"; I = "instrumental"; O = "other"
LISTS = {
"粤": [
 ("7ANIoOroUEo","咸水歌（中山，曲目未标）","广东中山","咸水歌",Y,"local 咸水歌 singers, 龍鸣 channel"),
 ("lBok4B9roa0","咸水歌·十八相送","广东中山坦洲","咸水歌",Y,"folk singers 容妹、谭妹"),
 ("HKijKIGF9SE","咸水歌·陈世美","广东中山坦洲","咸水歌",Y,"folk singers 谭妹、容妹"),
 ("LvSaSFANT7Q","海底珍珠容易搵","广东中山","咸水歌",Y,""),
 ("zGxgmKzzVtQ","攞魚歌","澳门","咸水歌",Y,"咸水歌 bearer 何金沛"),
 ("q6stz5L-ve4","嘆生禮·嘆阿爹","珠三角/香港疍家","叹歌（疍家）",Y,"疍家 lament, field-style"),
 ("nHfssZrmYFM","行船歌（大船拋住沱濘頭）","珠三角/香港疍家","渔歌/咸水歌",Y,""),
 ("nxXbSC48XVw","儋州调声（传统）","海南儋州","调声",Y,"also in original region link list"),
 ("lAGz4EhGe3Q","儋州调声（本土唱法）","海南儋州","调声",Y,"live local singing"),
 ("FahgEXth4Mo","摇侬调","海南三亚崖州","崖州民歌",M,""),
 ("WFDmGoqEF9s","五指山歌","海南五指山","山歌（黎族民歌）",M,"CCTV 中国民歌大会"),
 ("4qcmnqaO9z4","叫侬唱歌侬就唱","海南","海南民歌",M,""),
 ("uidh7TkClhI","临高渔歌（哩哩美）","海南临高","渔歌",Y,"哩哩美 = 临高渔歌"),
 ("zB1ff5DqAHc","卖鸡调·懒婆娘","广东台山","卖鸡调（五邑民歌）",Y,"traditional Taishan folk singer"),
 ("-LdAjRYMWrg","賀年歌","广东台山","台山民歌",Y,"blind folk artist"),
 ("H09rVy6vKWg","禾樓歌（山歌論籮勿論篇）","广东台山","禾楼歌/山歌",Y,"archival antiphonal"),
 ("AJvMQCI9K6w","木鱼金兰腔·情歌对唱","广东台山","木鱼歌",Y,""),
 ("Sz8a0w8PlF4","木魚歌·陳世美","广东东莞石龙","木鱼歌",Y,""),
 ("xh8esX3Neyw","月光光","广东（广府）","童谣",O,"1936 recording, child star 黎铿"),
 ("HV-pCL6YReQ","落雨大","广东广州","童谣",O,"CCTV 中国民歌大会, children"),
 ("X5sIndwDEQc","卖懒","广东（广府）","童谣/年俗歌",O,"representative song"),
 ("40AJUf8E-Fk","氹氹转","广东（广府）","童谣",O,""),
 ("ZyOeDJ7USmQ","汕尾渔歌·斗歌","广东汕尾","渔歌",Y,"汕尾疍家渔歌 (sung in 汕尾白话)"),
 ("XJ1sdYU2rU0","龙舟歌（龙舟说唱）","广东顺德","龙舟说唱",Y,"field recording; narrative-song genre"),
 ("yoPK17B4TyU","咸水歌（中山，曲目未标）","广东中山","咸水歌",Y,""),
 ("6CA15Aszbgk","水乡情（高堂歌）","广东中山","高堂歌（咸水歌）",M,"高堂歌 style of 咸水歌"),
 ("lPIY7TStzdI","大澳舢舨歌謠","香港大澳","咸水歌",Y,"old boat-dweller singer 玲姐"),
 ("uaYpQM8Y5U8","蜑家船歌","珠三角疍家","渔歌/咸水歌",Y,""),
 ("KX4YwtcEaAI","嘱姑九点半","海南儋州","调声",M,"popular 调声 piece"),
 ("b0kwMFUlS3M","摇侬调","海南三亚崖州","崖州民歌",O,""),
 ("wC-BJrPkTPw","五指山歌","海南五指山","山歌（黎族民歌）",M,"顾莉雅"),
 ("SljsPz-SRRI","久久不见久久见","海南","海南民歌",M,"with orchestra"),
 ("F5HyFMwB2fg","久久不见久久见","海南","海南民歌",O,""),
 ("-LS2z9bp1Ls","卖鸡调·退聘禮","广东台山","卖鸡调（五邑民歌）",Y,"陈玲玉"),
 ("vfKvSnj9Efs","卖鸡调（老一辈唱法）","广东台山","卖鸡调（五邑民歌）",Y,"伍伯相、梁茹芳"),
 ("vyjGJFQl1eY","木鱼（台山阿姆唱）","广东台山","木鱼歌",Y,""),
 ("l0ucGq9v1SE","月光光","广东（广府）","童谣",O,""),
 ("-Z0Vvm-yy7w","落雨大","广东广州","童谣",O,"solo Cantonese"),
 ("ii8U3EOVo2M","鸡公仔","广东（广府）","童谣",O,""),
 ("5EKOaxgl6zo","汕尾渔歌","广东汕尾","渔歌",Y,""),
],
"客家特区": [
 ("cyPGGncGAm4","客家山歌对唱（五华妹与93岁阿婆）","广东兴宁/五华","山歌",Y,"elderly tradition bearer"),
 ("5L0K_jUeENI","客家山歌（91岁阿婆）","广东梅州兴宁","山歌",Y,""),
 ("zdyYFts6lUE","客家山歌（龙岩）","福建龙岩","山歌",Y,"field recording"),
 ("n9ZLmdByctc","梅縣情歌","广东梅县","山歌",M,"1956 HK recording"),
 ("qRAQvCp4hxs","老山歌·採茶","台湾（桃竹苗）","老山歌",Y,"王鳳珠"),
 ("BF-cFn4DcyE","山歌子·客家花","台湾（桃竹苗）","山歌子",Y,"王鳳珠"),
 ("KbaNc8UCkZo","平板·飲水思源","台湾（桃竹苗）","平板",Y,"王鳳珠"),
 ("w_Tm08XqP9E","山歌仔·冬梅","台湾（桃竹苗）","山歌仔",Y,"王鳳珠"),
 ("4p87lfkeLcg","兴宁山歌","广东兴宁","山歌",Y,"中国音乐地图"),
 ("rRZBWlDuU7Q","丰顺山歌","广东丰顺","山歌",Y,"中国音乐地图"),
 ("hIxA5inYmYc","百花山上","福建闽西","山歌",Y,"中国音乐地图"),
 ("WmgF16BlmJw","犁田歌","福建闽西","山歌/劳动歌",Y,"中国音乐地图"),
 ("Tobw4tclFB8","十跌古","福建闽西","山歌",Y,"中国音乐地图"),
 ("AJrkviaKPdo","采桑歌","福建闽西","山歌",Y,"中国音乐地图"),
 ("MlmCTzYoG-A","阿哥出门往南洋","福建闽西","山歌",Y,"中国音乐地图"),
 ("O5gm8EkS9ws","老妹好比桂花树","湖南浏阳","客家山歌",Y,"浏阳客家; 中国音乐地图"),
 ("jBC_Rx1IXkI","客家盘歌","湖南浏阳","盘歌",Y,"浏阳客家; 中国音乐地图"),
 ("xPcc4AJpN88","广东上来一个人","湖南浏阳","客家山歌",Y,"浏阳客家; 中国音乐地图"),
 ("EKzBFVYbrP8","客家山歌好出名","广东梅州","山歌",Y,"中国音乐地图"),
 ("WLseIb-dkbc","十二月古人","台湾","山歌/小调",Y,"鄧滿妹、陳秀鳳 archival"),
 ("HhwBQMqQCVE","老十二月古人","台湾（新竹）","小调",Y,"徐木珍"),
 ("_WK2A-n-93Q","老山歌","台湾","老山歌",Y,"張美珍"),
 ("byhvICWMMfQ","平板","台湾","平板",Y,"謝其國"),
 ("hrFlrlHT4ZA","天公落水","台湾","童谣/民谣",M,"古慧慧"),
 ("tb3ZwHwKcRM","天公落水","台湾","童谣/民谣",O,""),
 ("UaEpYiBj2LM","月光光","江西赣南","童谣",O,""),
 ("zvjsoWQGA0I","月光光秀才郎","广东梅州","童谣",Y,"张琳"),
 ("PSVThcBBsLo","月光光（客家童謠）","台湾","童谣",O,"also in original region link list"),
 ("Etwt-1wHFZE","送郎","台湾","山歌/小调",M,"陳明珠"),
 ("9hMlusxAYww","送郎","台湾美浓（六堆）","美浓山歌",Y,"古堂財、李喜娣"),
 ("NMs55CqXVl8","送郎过番","广东梅州","山歌",Y,""),
 ("L7z9iLv93ig","摇篮歌","台湾美浓（六堆）","美浓山歌",Y,"古堂財、李喜娣"),
 ("p-DXr5WjBrk","半山謠","台湾美浓（六堆）","美浓山歌",Y,"古堂財、李喜娣"),
 ("wUGaaaI7l3A","落水天","广东梅州","山歌",M,"黄穎, labelled 传统山歌"),
 ("WfKvD29EuR4","竹叶撑船你爱来","广东梅州","山歌",M,"labelled 传统山歌; closest to 风吹竹叶"),
 ("93QlBexLpPA","嬲到日頭轉西山","广东河源","山歌",Y,"陳菊芬"),
 ("gXKAh0fUSN0","闽西山歌","福建龙岩","山歌",Y,"吴金发"),
 ("pHqgt8FM-DM","梅州传统山歌·情歌对唱","广东梅州","山歌",Y,""),
 ("pfzlivLiIWw","有好山歌溜等来","广西贺州","山歌/歌谣",Y,""),
 ("qNT2xk_noYI","客家山歌（传统）","未详","山歌",Y,"short but >60s"),
],
"江汉": [
 ("LnocpjXtNRc","啰啰咚","湖北监利","田歌（啰啰咚）",Y,"field recording"),
 ("zOPBI40ROqU","月望郎","湖北仙桃（沔阳）","小调",Y,"原生态 folk singer"),
 ("yX6PlQPfTdE","补背褡","湖北仙桃（沔阳）","小调",Y,""),
 ("wIOG1XX-YkY","哪有闲空回娘家","湖北仙桃（沔阳）","小调",Y,""),
 ("Y8ObEeqS0jg","反照花台","湖北仙桃（沔阳）","小调",Y,""),
 ("nv9Ykq9s_K0","姑娘送你咚咚锵","湖北仙桃（沔阳）","小调",Y,""),
 ("5ZbIgssct_8","到春来呀百花开呀","湖北仙桃（沔阳）","小调",Y,""),
 ("ypw84SPR-Ug","幸福歌","湖北江汉平原","小调",Y,""),
 ("0mvTb2kX7W0","信阳民歌","河南信阳","山歌/小调",Y,"field recording"),
 ("J0uzr2CaCkA","信阳民歌","河南信阳","山歌/小调",Y,"field recording, different item"),
 ("xPPfLpMRyjA","神农架花鼓歌","湖北神农架","花鼓歌",Y,""),
 ("dWyZ7mjANfM","撒叶儿嗬（跳丧）","湖北鄂西（土家族）","丧歌",Y,""),
 ("1gE4yho_znQ","神农溪土家族山歌","湖北巴东","山歌",Y,""),
 ("U1tVdxbm8DI","卖马调","湖北长阳","小调",M,""),
 ("iYwg8oM-yCE","卖篾货","湖北长阳","小调",M,""),
 ("BDUMaSSv2Wk","嗺咚嗺","湖北","田歌/小调",M,"周友金"),
 ("-OerjbkiY7c","催咚催","湖北","田歌/小调",M,""),
 ("AMzX-KDWSbA","车水情歌","湖北","车水歌（田歌）",M,""),
 ("EKIdL8AKRbU","一支山歌飞出崖","湖北","山歌",M,""),
 ("CRuTdN8wW6g","绣荷包","湖北荆州马山","小调",M,""),
 ("ftZdTrTUGbc","绣荷包","湖北","小调",M,"吴碧霞"),
 ("9TH4BhGFqvE","哪有闲空回娘家","湖北","小调",M,"蒋桂英 1958"),
 ("IqzboWeGius","一把芝麻撒上天","湖北浠水","小调",M,""),
 ("1fSojWskbtM","龙船调","湖北利川","灯歌",M,"宋祖英"),
 ("ZSCJAMaLuUY","龙船调","湖北利川","灯歌",M,""),
 ("vvsup0_wXGo","龙船调","湖北利川","灯歌",M,"于翌欣"),
 ("dRh0WCJk-Ds","洪湖水浪打浪","湖北洪湖","歌剧选曲（据民歌改编）",M,"original singer 王玉珍; representative song, composed on folk material"),
 ("gw19Y04P4s8","洪湖水浪打浪","湖北洪湖","歌剧选曲（据民歌改编）",M,""),
 ("a7YXlcnn8Co","洪湖水浪打浪","湖北洪湖","歌剧选曲（据民歌改编）",M,"彭丽媛"),
 ("NWvJcOgwziQ","黄四姐","湖北建始","喜花鼓",M,"陈涓"),
 ("CXFd0AUy4rU","黄四姐","湖北建始","喜花鼓",M,"覃诚芳"),
 ("ZrvNQTmeIYE","六口茶","湖北恩施","小调（土家族）",M,""),
 ("X4G_8BPPAqY","六口茶","湖北恩施","小调（土家族）",M,""),
 ("qgJRENoIm-U","六口茶","湖北利川","小调（土家族）",O,""),
 ("HxVpIAAM2a4","土家迎客歌","湖北恩施","小调（土家族）",M,""),
 ("m6HbgBIK0kQ","幸福歌","湖北天门","小调",M,"彭媛"),
 ("wINEGZ6pdmc","太阳过了河","湖北十堰","山歌",M,""),
 ("_GCS_Cxt8tg","伙计歌","湖北恩施","小调（土家族）",M,""),
 ("wkxvUsNKbRc","利川小曲","湖北利川","小曲（说唱）",Y,"field recording, narrative"),
 ("yC8iHRv_Nk0","月望郎","湖北仙桃（沔阳）","小调",Y,""),
],
"湘": [
 ("7WUzP04jGHI","古丈山歌","湖南古丈","高腔山歌",M,"何纪光"),
 ("iC9yTpDVeSY","郎在外间打山歌","湖南长沙","山歌",M,"何纪光"),
 ("_MVFQjco3ns","扯白歌","湖南湘西","山歌",M,"何纪光"),
 ("K_7JlabBnac","郎在高山打一望","湖南桑植","山歌",Y,"中国音乐地图"),
 ("33oUosoxL2I","欠姐歌","湖南桑植","山歌",Y,"中国音乐地图"),
 ("TITIMBYM4vI","娘试女","湖南桑植","小调",Y,"中国音乐地图"),
 ("NsGQtTxlIsw","槐树花儿香","湖南桑植","山歌",Y,"中国音乐地图"),
 ("2iBrbZjjSw8","板栗开花一条线","湖南桑植","山歌",Y,"中国音乐地图"),
 ("lBuYY_cn8Vo","芭蕉树上挂红灯","湖南桑植","山歌",Y,"中国音乐地图"),
 ("p93ke4-XSrQ","四川下来蹲蹲儿岩（上四川）","湖南桑植","山歌",Y,"中国音乐地图"),
 ("ucvwdvPxjzs","春季劝男","湖南长沙","小调",Y,"中国音乐地图"),
 ("_paVphckc9A","山歌无姐做不成","湖南长沙","山歌",Y,"中国音乐地图"),
 ("8V2Yv9EPfE4","洞庭号子","湖南洞庭湖","号子（渔歌）",Y,"中国音乐地图"),
 ("nlzPk8P1PvE","恰茶歌","湖南洞庭湖","渔歌",Y,"中国音乐地图"),
 ("Fc3-3vOyDdw","特特歌","湖南洞庭湖","渔歌",Y,"中国音乐地图"),
 ("mylPyi8efCU","蓑衣歌","湖南洞庭湖","渔歌",Y,"中国音乐地图"),
 ("Bq4txMD5F4A","坐堂歌","湖南湘西（苗族）","苗歌",Y,"中国音乐地图"),
 ("qDObl3MlNTo","织锦情歌","湖南湘西（土家族）","情歌",Y,"中国音乐地图"),
 ("2Zndyl4Bqfg","召市五句歌","湖南龙山（土家族）","五句子山歌",Y,"中国音乐地图"),
 ("94pRQwajjsE","训女词","湖南永州江永","女书歌",Y,"中国音乐地图"),
 ("0tab4L1fE9A","金坨女","湖南永州江永","女书歌",Y,"中国音乐地图"),
 ("zuP5bN2NnZM","马桑树儿搭灯台","湖南桑植","山歌",Y,"吴廷翠 (folk singer) & 杨一方"),
 ("Z3OC9hNVbzA","马桑树儿搭灯台","湖南桑植","山歌",M,"龙仙娥"),
 ("MyTOAeEKgog","马桑树儿搭灯台","湖南桑植","山歌",M,""),
 ("KNBsle69H9Y","郎在高山打一望","湖南桑植","山歌",O,""),
 ("qhdiFYd6TxI","郎从门前过","湖南桑植","山歌",M,""),
 ("CBWLjShyFTw","棒棒捶在岩板上","湖南桑植","山歌",M,"仝卓"),
 ("ki5x1qnxAf4","伴嫁歌","湖南嘉禾","伴嫁歌",Y,""),
 ("ILlNjy3d6Mo","姐姐出嫁","湖南嘉禾","伴嫁歌",Y,""),
 ("V5-Ww-vpDRk","哭嫁歌","湖南湘西（土家族）","哭嫁歌",O,""),
 ("1q1-RaQLbow","澧水船夫号子","湖南澧水","号子",O,""),
 ("-1XOiPn0xFw","澧水船夫号子","湖南澧水","号子",M,"male a cappella chorus"),
 ("Jfy4F0OWI10","洗菜心","湖南","花鼓小调",M,"吴碧霞"),
 ("Ugxu8-jiiWA","采茶（湖南花鼓）","湖南","花鼓小调",M,"鞠秀芳"),
 ("7pqOE21s7nQ","一根竹竿容易弯","湖南","小调",M,"何纪光"),
 ("IZdliTzVOEg","四季花儿开","湖南","小调",M,"representative song"),
 ("8vD5B3xnhGQ","浏阳河","湖南浏阳","创作民歌（花鼓调）",M,"representative; 1950s song on 花鼓 tune"),
 ("ZYBpysy5oqY","浏阳河","湖南浏阳","创作民歌（花鼓调）",M,"宋祖英"),
 ("niUi-cWgmXQ","挑担茶叶上北京","湖南","创作民歌",M,"representative; 何纪光"),
 ("14z4NLC8D4Y","刘海砍樵","湖南长沙","花鼓戏选段",M,"representative; opera excerpt (花鼓戏)"),
],
"赣": [
 ("pq6lh-AVC9M","江西传统民歌（龙虎山船家）","江西鹰潭龙虎山","船歌/小调",Y,"boatman singing, field"),
 ("dIbkBl9pL-Y","兴国山歌","江西兴国","山歌",Y,""),
 ("7PbZoKH12cA","兴国山歌","江西兴国","山歌",Y,""),
 ("SmPQpZQP6B0","打支山歌过横排","江西兴国","兴国山歌",M,""),
 ("A3jsSBv0bTA","打支山歌过横排","江西兴国","兴国山歌",O,""),
 ("KMAQXHLEZcY","打支山歌过横排","江西兴国","兴国山歌",M,"徐子尧"),
 ("uRPilTtZZRE","斑鸠调","江西赣南","采茶调/小调",M,"黄玉英"),
 ("Md_DDGyAJxg","斑鸠调","江西赣南","采茶调/小调",O,""),
 ("xnIrEnrZzeo","斑鸠调","江西赣南","采茶调/小调",M,"吴碧霞"),
 ("-gvCbLpZKBQ","红绣鞋","江西赣南","小调",M,"黄玉英"),
 ("dVXakn52YUs","割韭菜","江西赣南","小调",M,"黄玉英"),
 ("aueyg3cHMDk","打鞋底","江西赣南","小调",M,"黄玉英"),
 ("xOx_0pQKsUU","瓜子仁","江西赣南","小调",M,"黄玉英"),
 ("iM4W0CEZAqs","闹五更","江西赣南","小调",M,"黄玉英"),
 ("zuecP79NphI","牡丹调","江西赣南","小调",M,"黄玉英"),
 ("6YwMXhnAacY","长铜钱歌","江西赣南","小调",M,"黄玉英"),
 ("eFRoS9tU6ek","照镜子","江西赣南","小调",M,"黄玉英"),
 ("8o_yZfpN1P8","睄妹子","江西赣南","小调",M,"黄玉英"),
 ("yWo9FjUFq6g","双牵手","江西赣南","小调",M,"黄玉英"),
 ("gP_MHf7QKvk","长歌（送郎调）","江西赣南","采茶调",M,"黄玉英"),
 ("OPblXc1nYwA","姐在房中","江西赣南","小调",M,"黄玉英"),
 ("wHT8lIYxfJw","倒采茶","江西石城","采茶调",M,"黄玉英"),
 ("8VJa8w3tkE8","送表哥","江西赣南","采茶调",M,""),
 ("jPJlt9VQdDg","送郎调","江西赣南","采茶调",M,"卢致苑、周欢"),
 ("zfjhhsLbPaw","送郎调","江西赣南","采茶调",M,""),
 ("Kvvy0eOsge8","青草小河边","江西","牧童山歌",O,"children's group; representative song"),
 ("QTQKOQOVP-Y","武宁打鼓歌","江西武宁","薅草锣鼓（田歌）",Y,""),
 ("GjdYYhQ5Chc","哭嫁","江西吉安遂川","哭嫁歌",Y,"客网 field video; Hakka village in 赣"),
 ("RTIv-JdLzZE","十送红军","江西","革命民歌（据赣南送郎调）",M,"representative song"),
 ("SBymLbSl6f4","十送红军","江西","革命民歌（据赣南送郎调）",O,"sung by veteran Red Army propaganda members"),
 ("3L1gUNezwKw","请茶歌","江西","茶歌（创作民歌）",M,"representative; 任桂珍"),
 ("9UrOQIk3L_0","请茶歌","江西","茶歌（创作民歌）",M,"张也"),
 ("0LUkAlyQUE0","映山红","江西","电影歌曲（江西民歌风）",M,"representative; composed in Jiangxi folk style"),
 ("VM1vybDLfig","不唱山歌心不爽","江西","山歌",O,"choral arrangement"),
 ("0e4Xp1y1Ynk","萍乡童谣","江西萍乡","童谣",O,"provenance uncertain"),
 ("Gh8Tbr-7qLc","江西童谣","江西","童谣",O,"胡蓉蓉; old recording"),
 ("yWLYxgwtEM4","上茶山","江西赣南","茶歌（器乐）",I,"instrumental (方锦龙)"),
 ("874CV3skQsI","十怨妹","江西赣南","采茶调（器乐）",I,"instrumental"),
 ("0gTohrBCIXg","心中自有小百灵","江西赣南","小调",M,"黄玉英; labelled 赣南民歌, could be a newer song"),
 ("Bu_KGdOKkHo","送郎调","江西赣南","采茶调",M,"CCTV 中国民歌大会; 67 s"),
],
}

for region, items in LISTS.items():
    audio = ROOT / "data/regions_audio" / region
    out, seen = [], set()
    for rank, (vid, song, area, genre, perf, note) in enumerate(items, 1):
        assert vid not in seen, (region, vid); seen.add(vid)
        info = audio / f"{vid}.info.json"
        dl = info.exists()
        if vid in meta:
            h = meta[vid]; title, ch, dur = h["title"], h["channel"], h["duration_s"]
        else:
            j = json.load(info.open()); title, ch, dur = j["title"], j.get("uploader") or j.get("channel"), j.get("duration")
        sq = srcq.get((region, vid)) or srcq.get(("*", vid)) or "already_downloaded (earlier region link list)"
        assert dur is None or 60 <= dur <= 720, (region, vid, dur)
        out.append({"rank": rank, "video_id": vid, "url": f"https://www.youtube.com/watch?v={vid}",
                    "title": title, "channel": ch, "duration_s": int(dur) if dur else 0,
                    "song_name": song, "province_or_area": area, "genre": genre,
                    "performance_type": perf, "already_downloaded": dl, "source_query": sq, "note": note})
    from collections import Counter
    c = Counter(o["song_name"] for o in out)
    print(region, len(out), "distinct", len(c), "dl", sum(o["already_downloaded"] for o in out),
          "over3", [k for k, v in c.items() if v > 3])
    (ROOT / f"data/regions_curated/{region}.json").write_text(json.dumps(
        {"region": region, "curated_on": "2026-09-28", "candidates": out}, ensure_ascii=False, indent=1))
