from sw_build import build
Y="原生态"; M="民族唱法"; I="instrumental"; O="other"
H="汉族"
xn = [
("_3sI_PtkRTU","川江号子",H,"重庆","号子/劳动歌",Y,"former Yangtze boatmen performing 大江船歌"),
("StgvMIiW08s","川江号子",H,"四川/重庆","号子/劳动歌",Y,""),
("zValxC-jzqA","柳街薅秧歌",H,"四川成都温江","薅秧歌/田歌",Y,"非遗 village performance"),
("b02z2cEe4ng","冬寒菜",H,"四川","小调",Y,"Rhymoi 中国音乐地图 field-style recording"),
("AT1lowVR8UY","太阳出来喜洋洋（石柱啰儿调）","土家族/汉族","重庆石柱","啰儿调/山歌",Y,"traditional-bearer 杨中合; source form of 太阳出来喜洋洋"),
("lAtp0PZY3SA","云南山歌（花灯调）",H,"云南","山歌",Y,"amateur village field recording"),
("PLziBckREhA","云南山歌",H,"云南","山歌",Y,"amateur village field recording"),
("ANoml74LnnQ","南坪小调",H,"四川阿坝九寨沟（南坪）","小调/南坪曲子",Y,"Han 南坪曲子 tradition"),
("8l1yhALLo1c","小河淌水",H,"云南弥渡","山歌/小调",M,"黄虹 1953 recording, earliest classic"),
("rpDdNukM64Q","小河淌水",H,"云南弥渡","山歌/小调",M,"original region link; confirmed live in search"),
("0Pn6HchMovo","猜调",H,"云南昆明","小调/对歌",M,"黄虹 1956 live"),
("ZrZEfe8Mh4s","赶马调",H,"云南","山歌",M,"黄虹 1956 live"),
("fMcewGlJEz8","放马山歌",H,"云南玉溪","山歌",M,"黄虹"),
("GhQAoqnkpzM","弥渡山歌",H,"云南弥渡","山歌",M,"黄虹"),
("Z2Kt9UShBZA","耍山调",H,"云南","山歌",M,"黄虹"),
("7ylXz05-HOM","白鹤双双飞下来",H,"云南姚安","山歌",M,"黄虹"),
("MsVeR1mllq0","月牙弯弯映小河",H,"云南大姚","山歌",M,"黄虹"),
("CsqtVIqLdfQ","高山砍柴",H,"云南","山歌",M,"黄虹"),
("jlT0dTIoTrY","太阳出来喜洋洋",H,"四川/重庆","山歌",M,"蔡绍序 historical recording"),
("UIQQnV2CfI0","槐花几时开",H,"四川宜宾","山歌",M,"蔡绍序"),
("E_L3naWc6_0","槐花几时开",H,"四川宜宾","山歌",M,"compares Sichuan vs Yunnan singing styles"),
("0lD_dLxdu9I","槐花几时开",H,"四川宜宾","山歌",M,"original region link; confirmed in search"),
("jw3tQwFRgCA","康定情歌",H,"四川康定","小调/溜溜调",M,"喻宜萱 historical recording; lyric video"),
("nE-sLijay0A","康定情歌",H,"四川康定","小调/溜溜调",M,"original region link; CCTV 中国民歌大会"),
("K6VhJlESchM","康定情歌",H,"四川康定","小调/溜溜调",M,"original region link"),
("OQ2vNwJ9eTw","溜溜山歌",H,"四川","山歌",M,""),
("mzLkgqIR2dE","黄杨扁担",H,"重庆秀山","花灯调/小调",M,""),
("IJX_dFfh-4U","黄杨扁担",H,"重庆秀山","花灯调/小调",M,""),
("yMQjYfuxtzo","采花",H,"四川","小调",M,"彭丽媛 1990"),
("x7qEZhdTtQw","采花",H,"四川","小调",M,"中央歌舞团女声合唱队 (choral)"),
("trX6KTdoTlY","采花",H,"四川","小调",M,""),
("ujmD1UzUjOc","绣荷包",H,"云南弥渡","小调",M,"Yunnan (Midu) 绣荷包, not the Shanxi song"),
("ZTlAf7R7ncM","绣荷包",H,"云南","小调",M,"Yunnan version"),
("mYIpK0yZSrU","大河涨水沙浪沙",H,"云南","山歌",M,"刘淑芳"),
("9JO1RIlZCxM","放马山歌",H,"云南玉溪","山歌",M,"彭丽媛; 69 s"),
("up6N00CGhhI","螃蟹歌",H,"四川","小调/儿歌",M,""),
("aHDCg_n5oBQ","情姐下河洗衣裳",H,"贵州","小调",M,"Guizhou coverage"),
("9RDYdUUxh8c","情姐下河洗衣裳","仡佬族/汉族","贵州道真","小调",Y,"local 道真 performance"),
("jQGqaK7SbZA","猜调",H,"云南昆明","小调/对歌",M,""),
("6vgd3X-WZrc","太阳出来喜洋洋",H,"四川/重庆","山歌",M,"original region link"),
]
build("西南高原", xn)

R="Rhymoi 中国音乐地图 recording of local tradition-bearers"
dm = [
("othoEuLuXSQ","夏蝉之歌","侗族","贵州黔东南","侗族大歌",Y,"original region link; "+R),
("TOG1umDJjKY","松鼠歌","侗族","广西三江","侗族大歌",Y,R),
("CU3o7a-FAE4","撑船歌","侗族","广西三江","侗族大歌",Y,R),
("gb3DqTR84fM","高山井水歌","侗族","广西","侗族大歌",Y,R),
("HZz-B4dZUiM","出嫁歌·八月半","侗族","贵州","侗族民歌/婚俗歌",Y,R),
("Ydep74YX0zQ","侗家敬酒歌","侗族","贵州","酒歌",Y,R),
("h3ALoKV6mlg","革东飞歌","苗族","贵州剑河革东","苗族飞歌",Y,"original region link; "+R),
("Ijq1hsCA5lI","久仰飞歌","苗族","贵州剑河久仰","苗族飞歌",Y,"original region link"),
("XAtSXTQTczE","苗族飞歌","苗族","云南","苗族飞歌",Y,"Yunnan Village Music field recording"),
("OAS8V7pr15U","站在高高的苗岭","苗族","贵州","苗族民歌",Y,R),
("yWo3JwEpZ8A","春之歌","苗族","贵州","苗族民歌",Y,R),
("tnbM2gKiXQo","毕节苗歌（Kwv Txhiaj）","苗族","贵州毕节","苗族民歌",Y,"原生态 Miao song"),
("BY2UzpV_67M","彝族牧歌","彝族","贵州","牧歌",Y,"original region link; "+R),
("1ypImBsL_Ds","阿诗玛叙事长诗（第一段）","彝族（撒尼）","云南石林","叙事长诗",Y,"traditional Sani Ashima epic, not the 1964 film songs; "+R),
("-O3sWvWdc8U","打歌·海菜腔","彝族","云南石屏/红河","海菜腔",Y,"CCTV 中国民歌大会, tradition-bearers"),
("Cij77-BKgT4","哭嫁调","彝族","云南","婚俗歌",Y,R),
("NKNiYVn-VP4","赶牛调","彝族","云南","山歌",Y,R),
("aY14KFrayFw","弥渡彝族山歌","彝族","云南弥渡","山歌",Y,"Yunnan Village Music field recording"),
("N4G8QHDjtfI","啦噶飘","彝族（他留人）","云南丽江永胜","情歌",Y,"Yunnan Village Music field recording; 528 s"),
("SWwAgfVtYRk","梅葛·相遇调","彝族","云南楚雄姚安","梅葛",Y,"Yunnan Village Music field recording; 515 s"),
("_RrD4HHGvrU","哈尼族多声部民歌","哈尼族","云南红河","多声部民歌",Y,"ethnographic field recording (dbadagna); 551 s"),
("SM7DuHsV4nI","爱伲人摇篮曲","哈尼族（爱伲）","云南西双版纳","摇篮曲",Y,R),
("LcXA95RnigM","父母恩","哈尼族","云南","哈尼族民歌",Y,R),
("6e515bjubmc","日夜相守（长嘹）","壮族","广西","壮族嘹歌",Y,R),
("vKvjIOT2C9M","那坡山歌","壮族","广西百色那坡","山歌",Y,R),
("pDhI6OWU8zs","壮族山歌对唱（鱼峰歌圩）","壮族","广西柳州","歌圩对歌",Y,"amateur field recording of 歌圩 antiphonal singing"),
("lxj7e6ilPB0","好花红","布依族","贵州惠水","布依族民歌",M,""),
("jJWxEf5Psas","山上独木树","傈僳族","云南怒江","傈僳族民歌",Y,R+"; 422 s"),
("1-qNRG_Nl64","傈僳古调","傈僳族","云南怒江","古调",Y,R),
("bvdRfN4PbZM","想念我的家乡","纳西族","云南丽江","纳西族民歌",Y,R),
("TMkKLFFdBW4","三月是春天","纳西族","云南丽江","纳西族民歌",Y,R),
("K--BxGgHnlk","天上的月亮（摇篮曲）","佤族","云南沧源/西盟","摇篮曲",Y,R),
("6lmxsCcOy3U","田埂调","白族","云南大理","白族调",Y,R),
("IWpLihBSXhA","放羊调","白族","云南大理","白族调",Y,R),
("Yyhl3tn2_U4","泥鳅调","白族","云南大理","白族调",Y,R),
("_DnkGQcxfKc","剑川调","白族","云南剑川","白族调",Y,R),
("u3dZLHZq0IA","西山调","白族","云南洱源西山","白族调",Y,R),
("vZU73xs3nQ0","背盐调","白族","云南大理","白族调",Y,R),
("CoL1ASLucUY","耍龙调","白族","云南大理","白族民歌",Y,R+"; labelled 'folk music' – verify vocal"),
("qXvCnzz-Da4","迎客歌","苗族","湖南湘西","苗族民歌",Y,R+" (湘西 is in region's partial western Hunan)"),
]
build("西南多民族古老原始文化民歌区", dm)

T="藏族"
tb = [
("Jjbk3CK0RBM","香格里拉山歌",T,"云南迪庆","山歌（鲁）",Y,"field recording of open-air mountain song"),
("ZsnaEybzIK4","扎西拉鲁（吉祥山歌）",T,"西藏","山歌（鲁）",Y,R),
("-vQEx3cpsI0","鲁孜鲁（放羊山歌）",T,"西藏","山歌（鲁）",Y,R),
("0ScZE0eqQ4s","亚吉查姆（最美的家乡）",T,"西藏","藏族民歌",Y,R),
("jUZEBYXkK-c","达朵瓦（骏马）",T,"西藏","藏族民歌",Y,R),
("Q9MAzgqHrhY","诺拉琼（黑色牦牛）",T,"西藏","藏族民歌",Y,R),
("rrzuEQwOWE0","夏松夏（月亮映照山岭）",T,"西藏","藏族民歌",Y,R),
("L0IC3ELtQIs","蕞（藏羚羊在奔跑）",T,"西藏羌塘","藏族民歌",Y,R),
("dpP2vB7SLxo","阿古强巴（雪后的太阳）",T,"西藏","藏族民歌",Y,R),
("VTOm9Nef1hQ","雄雅日（上部山）",T,"西藏","藏族民歌",Y,R),
("C6cln8f4WX8","芒康酒歌（碧玉一样的山谷）",T,"西藏昌都芒康","酒歌（羌谐）",Y,R),
("uSN27yyrkCI","日穆巴坚（云雾缭绕的山）",T,"西藏","藏族民歌",Y,R),
("2ydRrqbHOY8","日吞布（高高的珠峰）",T,"西藏日喀则","藏族民歌",Y,R),
("ZdkUw2z7sAA","岗堆吞布（雪山顶上）",T,"西藏","藏族民歌",Y,R),
("cq0qk9Wy0ns","央金朵朵",T,"西藏后藏","堆谐",Y,R),
("OR1XDKFKZIU","舒假啦（摇动的树）",T,"西藏","民间歌舞（谐）",Y,R),
("RdaRiSswSao","觉啦斯琼（英俊的少年）",T,"西藏","民间歌舞（谐）",Y,R),
("gxzupBxUj5Y","觉拉扎西（白日山下）",T,"西藏","民间歌舞（谐）",Y,R),
("F9kqLzE2D-o","吾夏甲庆玛布（红色毡帽上的花缎）",T,"西藏","民间歌舞（谐）",Y,R),
("2hpoFDj7tjE","卓姆仁钦岗（远行的人）",T,"西藏","民间歌舞（谐）",Y,R),
("-h_UvfEjHN0","吉白尼玛（东山顶上）",T,"西藏拉萨","囊玛",Y,"traditional 囊玛 version of 在那东山顶上; "+R+"; may be partly instrumental"),
("RGSfVDILpyQ","扎拉西巴（吉祥百花园）",T,"西藏拉萨","囊玛",Y,R+"; may be partly instrumental"),
("WNH-d21FgX4","珠桑桑（幸福的摇篮）",T,"四川藏区","藏族民歌",Y,R),
("Td-C28CdRuo","夏旭冬日（雪宝山顶）",T,"四川阿坝松潘","藏族民歌",Y,R),
("5XfZIS7rdfQ","来迪荣泰（听我们的祝福）",T,"四川藏区","藏族民歌",Y,R),
("8-7TPhDd4GE","幸福之歌",T,"青海（安多）","藏族民歌",Y,R),
("gJ3xt0bM4y8","心上的人",T,"青海（安多）","藏族民歌",Y,R),
("-ymWYNEaQLM","赞马歌",T,"青海（安多）","赞歌",Y,R),
("OaZEUUBuRD0","云山雾罩的家乡",T,"青海（安多）","藏族民歌",Y,R),
("bC7UiyNa5nc","华锐赞歌",T,"青海/甘肃华锐（天祝）","赞歌",Y,R),
("qne7wMTeZls","黑帐篷",T,"青海（安多）","牧歌",Y,R),
("iiDdTjUzF_Y","华锐拉伊",T,"青海/甘肃华锐（天祝）","拉伊（情歌）",Y,R),
("SWK_lqyttXU","然西娘荣（洁白的羊群）",T,"青海（安多）","牧歌",Y,R),
("D4nsXCInLKg","家乡的草原",T,"青海（安多）","藏族民歌",Y,R),
("_RjQZvMSOUU","夏仓郭仓",T,"西藏","堆谐",Y,"local 堆谐 performance"),
("9FrIKg83reI","阿玛勒火",T,"西藏拉萨","囊玛",M,"措香 (囊玛 tradition singer)"),
("DJd_MZTDTs4","可爱的布谷鸟（卓尼拉伊）",T,"甘肃甘南卓尼","拉伊",M,"Amdo/Gansu 拉伊, concert performance"),
("JyBupEVYRBI","北京的金山上",T,"西藏","藏族民歌（新词）",M,"original region link; traditional Tibetan tune with 1960s new lyrics – lower priority"),
("O-3nJURqHOQ","康巴酒歌",T,"四川甘孜/康区","酒歌",O,"Kham drinking song; performer/context unverified"),
("AioJGv9xG5U","羌谐（Changshay 酒歌）",T,"西藏","酒歌（羌谐）",O,"only plausibly traditional item among the 92 downloaded (rest are modern dance/pop/exile pop/shorts); 80 s clip, verify"),
]
build("藏族民歌区", tb)

U="维吾尔族"; K="哈萨克族"; TJ="塔吉克族"
xj = [
("1Hef5OXHr5I","Mitiz Meshrep（麦西来甫）",U,"新疆","麦西来甫民歌",Y,"original region link; info.json exists but audio missing, confirmed live in search"),
("52k7XPktTE8","Yultuzum（我的星星）",U,"新疆","维吾尔民歌",Y,""),
("PEH2FtIkAus","Gulyarxan（古丽亚尔汗）",U,"新疆","维吾尔民歌",Y,""),
("8zrmMNTOMHY","Körgili keldinglimu",U,"新疆","维吾尔民歌",Y,"labelled 'folk music' – verify vocal"),
("Z7DTJxKWVtM","Ayshemgul Memet 维吾尔传统民歌",U,"新疆","维吾尔民歌",Y,"live, vocals + tambur/dutar; 641 s, may contain >1 song"),
("iGGVf34N3wQ","伊拉克木卡姆（选段）",U,"新疆","十二木卡姆",M,"single muqam excerpt"),
("zeVlUL17NXc","十二木卡姆（选段）",U,"新疆","十二木卡姆",M,"242 s excerpt"),
("wP83AfHGH5c","在花园中遇见了我的情人",U,"新疆","维吾尔民歌",Y,R),
("8D7tbBkuisk","情人对你说",U,"新疆","维吾尔民歌",Y,R),
("_UpnaSEKlqU","马车夫之歌",U,"新疆","维吾尔民歌",Y,R),
("IsOWrh5LofY","伊犁的大路边",U,"新疆伊犁","伊犁民歌",Y,R),
("2LnC97Eh7u8","茹孜莱姆",U,"新疆","维吾尔民歌",Y,R),
("4yOCiE0oyjY","美丽的塔里克山",U,"新疆","维吾尔民歌",Y,R),
("8x7cWRmIq_c","让我看看你的脸",U,"新疆","维吾尔民歌",Y,R),
("wq8r9j8GVHE","好朋友",U,"新疆","维吾尔民歌",Y,R),
("vGIHmg9VJAc","牡丹汗",U,"新疆伊犁","伊犁民歌",Y,R),
("VfZHbP-C9bs","哈密木卡姆",U,"新疆哈密","哈密木卡姆",Y,"ethnographic field recording (dbadagna); 358 s"),
("ftOoFea6_jc","刀郎木卡姆",U,"新疆麦盖提","刀郎木卡姆",Y,"local performance, 102 s"),
("V2pIIRED1ho","摇篮曲",K,"新疆北疆","哈萨克民歌",Y,R),
("GuE5wzCSBqQ","古丽迭热阿依木",K,"新疆北疆","哈萨克民歌",Y,R),
("Z-L9_m0tkPQ","蓝色的阔克河",K,"新疆北疆","哈萨克民歌",Y,R),
("3FilfLi9opI","阿合巴彦",K,"新疆北疆","哈萨克民歌",Y,R),
("mFgFLUkOw00","嘎克库（白天鹅在歌唱）",K,"新疆北疆","哈萨克民歌",Y,R),
("NGY5HIru7Bo","我的百灵鸟",K,"新疆北疆","哈萨克民歌",Y,R),
("E3KLmaYnhAk","哈利亚",K,"新疆北疆","哈萨克民歌",Y,R),
("QJrOHYQDWXY","Kerim Aiday（克里木阿依达）",K,"新疆","哈萨克民歌",Y,"CGTN VR clip, may include narration"),
("tiICOkEMA3o","法拉克（忧伤的爱情）",TJ,"新疆塔什库尔干","塔吉克民歌",Y,R),
("wt2ZwCMt5HI","巴拉马克",TJ,"新疆塔什库尔干","塔吉克民歌",Y,R),
("vyrCaHKKUZQ","萨热贡（一首古老的歌）",TJ,"新疆塔什库尔干","塔吉克民歌",Y,R),
("a_t2af7L35k","阿祖尔费克（思念故去的亲人）",TJ,"新疆塔什库尔干","塔吉克民歌",Y,R),
("TmjAdqAkXkw","达坂城的姑娘",U,"新疆达坂城","维吾尔民歌（王洛宾整理）",M,"Wang Luobin arrangement of folk tune"),
("Uq0lmS_L8As","半个月亮爬上来",U,"新疆","民歌（王洛宾整理）",M,"Wang Luobin arrangement"),
("w8mFxDlLLOM","半个月亮爬上来",U,"新疆","民歌（王洛宾整理）",M,"彭丽媛"),
("lGDE5z2WrBc","半个月亮爬上来",U,"新疆","民歌（王洛宾整理）",M,""),
("cz-0oyuzCHY","阿拉木汗",U,"新疆","维吾尔民歌（王洛宾整理）",M,""),
("qJ0Zv1YY7wg","掀起你的盖头来",U,"新疆","维吾尔民歌（王洛宾整理）",M,""),
("NmvPTnbQb-Y","掀起你的盖头来",U,"新疆","维吾尔民歌（王洛宾整理）",M,""),
("Nc2YtQNiRyM","燕子",K,"新疆","哈萨克民歌",M,""),
("k7dbkKi5f24","玛依拉",K,"新疆","哈萨克民歌",M,"殷秀梅"),
("rLDe2GVMvRg","青春舞曲",U,"新疆","维吾尔民歌（王洛宾整理）",M,""),
]
build("新疆民歌区", xj)

MG="蒙古族"; IM="内蒙古"
mg = [
("lcBDbaogtf8","孤独的白驼羔",MG,IM,"长调",Y,R),
("DXVnCHOdi4M","黑骏马",MG,IM,"长调",Y,R),
("7gxEFjYHDV4","汗山的雪",MG,IM,"长调",Y,R),
("FTLToWzfeH4","辽阔的草原",MG,"内蒙古锡林郭勒（乌珠穆沁）","长调",Y,R),
("rQXgHU1HdSY","温柔的春风",MG,IM,"长调",Y,R),
("0CNho28Ar18","圆蹄枣骝马",MG,IM,"长调",Y,R),
("13c_Qkkv4vs","褐色的雄鹰",MG,IM,"长调",Y,R),
("ncta7lrwOYY","调皮的枣红马",MG,IM,"长调",Y,R),
("dFHXHGD0Df0","小黄马",MG,IM,"长调",Y,R),
("8IXA7Ujc-TQ","矫健的骏马",MG,IM,"长调",Y,R),
("qc_kvoTVKHU","查干陶海故乡",MG,IM,"长调",Y,R),
("4nz0xy5KtFM","辽阔的草原",MG,"内蒙古锡林郭勒（乌珠穆沁）","长调",Y,"宝音德力格尔, master long-song singer"),
("ss8IRGB1pRU","走马",MG,IM,"长调",Y,"达瓦桑布"),
("Lby4rfR4MnA","Duuriimaa",MG,"蒙古国（跨境）","长调",Y,"Mongolia-side long song (UNESCO shared element)"),
("OPJ1WTF2SDY","Mongol Nutgiin Uzesgelen",MG,"蒙古国（跨境）","长调",Y,"Mongolia-side long song group"),
("hcIgvxdRlIw","Urtiin Duu",MG,"蒙古（未明）","长调",Y,"exact song unidentified"),
("Qr0WT-3TiZ4","赞颂成吉思汗",MG,"蒙古","赞歌/长调",Y,""),
("M1uV3wXUI6Y","牧歌",MG,"内蒙古呼伦贝尔","长调",Y,"阿木古楞、特仑, long-song version"),
("WsqX0Zz1lHo","牧歌",MG,"内蒙古呼伦贝尔","长调",M,"乌英嘎"),
("VScqK0NhleY","牧歌",MG,"内蒙古呼伦贝尔","长调（合唱改编）",O,"瞿希贤 choral arrangement – lowest priority for melody"),
("0ysiHGvz2X0","诺恩吉雅",MG,"内蒙古科尔沁","短调/叙事民歌",Y,R),
("ToAWzA7w2dE","吐尔基山",MG,IM,"短调",Y,R),
("3foZSFe8QyA","鄂尔多斯送亲歌",MG,"内蒙古鄂尔多斯","婚礼歌/短调",Y,R),
("UDASvgM0A1g","甘珠尔布日德",MG,"内蒙古呼伦贝尔","短调",Y,R),
("Z70PtcIQ1YI","圣主成吉思汗",MG,IM,"赞歌",Y,R),
("vmEhCMKfPTA","吉祥树",MG,IM,"短调",Y,R),
("WRCl1bp4pIo","六十棵榆树",MG,IM,"短调",Y,R),
("Ce2U9HNPxoQ","厄鲁特送亲歌",MG,"内蒙古（厄鲁特）","婚礼歌",Y,R),
("kKwd2UTpTzM","祝福新娘",MG,IM,"婚礼歌",Y,R),
("VDygbqzcsIQ","旷野",MG,IM,"短调",Y,R),
("Gm2Zf73zs_U","正月儿玛",MG,"内蒙古科尔沁","科尔沁叙事民歌",Y,""),
("ZMq-pGFXlXI","嘎达梅林",MG,"内蒙古科尔沁","科尔沁叙事民歌",M,"阿木古楞, CCTV"),
("GI4FngAG-Gs","嘎达梅林",MG,"内蒙古科尔沁","科尔沁叙事民歌",M,"腾格尔/哈拉木吉, TV gala"),
("5H1SRIzr-Rc","森吉德玛",MG,"内蒙古鄂尔多斯/锡林郭勒","短调",M,"梅林音乐团"),
("6twxZYYoJMg","鸿雁",MG,"内蒙古巴彦淖尔（乌拉特）","短调（新词）",M,"melody from 乌拉特 folk song 鸿嘎鲁, modern Chinese lyrics"),
("UE0bMNgmn-E","鸿雁",MG,"内蒙古巴彦淖尔（乌拉特）","短调（新词）",M,"see above"),
("zRJ1kDHpmgE","鸿雁",MG,"内蒙古巴彦淖尔（乌拉特）","短调（新词）",O,"amateur performance"),
("DXdpY9vn4IU","扎恩达勒",'达斡尔族',"内蒙古呼伦贝尔","扎恩达勒（山歌）",Y,"ethnographic field recording (dbadagna)"),
("sknMMCCCpYw","毛敖吉坎河",'鄂温克族',"内蒙古呼伦贝尔","鄂温克民歌",M,""),
("sbIizrbIam4","赞达仁",'鄂伦春族',"内蒙古/黑龙江","赞达仁（山歌）",M,""),
]
build("北方草原文化民歌区", mg)
