import csv, os
OUT = "/Users/sophiasun/Desktop/2cool4school/2026/aquarius/data/regions_curated/song_dates"
COLS = ["song_name", "region", "song_type", "origin_period", "earliest_attestation_year",
        "attestation_source", "composer_or_adapter", "composition_or_adaptation_year",
        "evidence_urls", "confidence", "notes"]
NA = "NA"

def R(song, typ="traditional", period=NA, year=NA, src=NA, comp=NA, cyear=NA, urls=NA, conf="low", notes=""):
    return dict(song_name=song, song_type=typ, origin_period=period, earliest_attestation_year=year,
                attestation_source=src, composer_or_adapter=comp, composition_or_adaptation_year=cyear,
                evidence_urls=" | ".join(urls) if isinstance(urls, list) else urls, confidence=conf, notes=notes)

NO_SRC = "no song-specific dated source found"
MOLIHUA_URLS = ["https://news.sina.com.cn/o/2009-11-23/020816650691s.shtml",
                "https://www.gzstv.com/a/b90bfff664614ff4bf6f3238b401d874",
                "https://zh.wikipedia.org/zh-hans/%E8%8C%89%E8%8E%89%E8%8A%B1_(%E6%B0%91%E6%AD%8C)"]
MOLIHUA_SRC = "李声振 heard 花鼓 with '好朵鲜花' lyrics in Beijing, 1756 (乾隆21); text in 《缀白裘》《花鼓》 (1767 edition); notation in Barrow 'Travels in China' 1804 and 《小慧集》 (1821 or 1837)"
MOLIHUA_NOTE = "Dates refer to the 鲜花调/茉莉花 tune family, not this regional variant specifically. 小慧集 date given as 1821 or 1837 in different sources."
ERZHUAN = "https://www.sohu.com/a/827144413_121124720"
TJ = "https://zh.wikipedia.org/zh-hans/%E5%A4%A9%E6%B4%A5%E6%97%B6%E8%B0%83"
HEBEI = "https://baike.baidu.com/item/%E6%B2%B3%E5%8C%97%E6%B0%91%E6%AD%8C/2698494"
SD = "https://baike.baidu.com/item/%E5%B1%B1%E4%B8%9C%E6%B0%91%E6%AD%8C/6600117"

data = {}
data["东北部平原"] = [
    R("丢戒指", urls=[ERZHUAN], notes="二人转小帽 repertoire; " + NO_SRC),
    R("包楞调", "traditional-adapted", "1960s", "1962", "lyrics collected by 魏传经 (成武县文化馆) from singer 周金英, 田集镇小程楼村, Oct 1962; tune notated by 孙啸天",
      "魏传经 (lyric collection/rewrite); 孙啸天 (谱曲)", "1962-1963",
      ["https://baike.baidu.com/item/%E5%8C%85%E6%A5%9E%E8%B0%83/278216", "https://k.sina.com.cn/article_7879776328_1d5abd84806802bqa0.html"], "medium",
      "Sung by 姚月兰 at the 1963 Shandong folk-song concert; 上海唱片社 record and 《歌曲》1963 no.4. Sources say 孙啸天 '谱曲', so how much of the melody is folk vs. arranged is unclear. The dataset includes a historic 1964 recording."),
    R("反正对花", urls=[HEBEI], notes="Liaoning variant of the 对花 question-and-answer type (cf. 昌黎 正对花/反对花 pair); " + NO_SRC),
    R("哭五更", urls=[TJ], notes="五更-form 小调 in the Tianjin 时调 milieu (genre said to date from Ming-Qing, flourishing late Qing); " + NO_SRC),
    R("回娘家", "newly-composed-folk-style", "1980s", "1982", "released as 《小媳妇回娘家》 by 邓丽君 on 宝丽金 album 《初次尝到寂寞》 1982",
      "汤尼 (翁清溪) music; 孙仪 lyrics", "1982",
      ["https://zh.wikipedia.org/zh-hans/%E5%B0%8F%E5%AA%B3%E5%A6%87%E5%9B%9E%E5%A8%98%E5%AE%B6", "https://baike.baidu.com/item/%E5%9B%9E%E5%A8%98%E5%AE%B6/20353894"], "medium",
      "'河北民歌' label goes back to 朱明瑛's 1984 CCTV Spring Festival Gala performance: the Taiwanese pop song was registered under 邓丽君's ancestral province. Confidence is medium only because the recording ('回娘家（河北民歌）', 民族唱法) is assumed to be this song rather than an unrelated Hebei tune; check the audio."),
    R("对花", urls=["https://lyj.cangzhou.gov.cn/lyj/c102444/201701/ad10f88f7a134889b3a993a72a8b10bc.shtml", HEBEI],
      notes="沧州 area 对花 (seasonal flower question-and-answer). 沧州 folk songs were compiled in Oct 1963 for 民歌集成, but inclusion of this song is not verified; " + NO_SRC),
    R("小拜年", urls=["https://zh.wikipedia.org/zh-cn/%E5%B0%8F%E6%8B%9C%E5%B9%B4", "https://culture.cnjiwang.com/cyjlwc/202503/3927767.html"],
      notes="Most-performed 二人转小帽; said to derive from a 营口 小调 (claim). Widespread on 二人转 stages from the 1960s, which is not a first attestation."),
    R("小放牛", "traditional-adapted", "late Qing", "1951", "《河北民间歌曲选》 1951 (collected by 晋察冀 cultural workers)",
      "侯俊山 (stage song-dance version)", "late 19th-early 20th c. (no exact year)",
      ["https://baike.baidu.com/item/%E5%B0%8F%E6%94%BE%E7%89%9B/23583367", "https://baike.weixin.qq.com/v117618957.htm"], "low",
      "Song-and-dance 小戏 on folk 小曲; sources credit the opera artist 侯俊山 with the stage version, first performed in Beijing theatres in late Qing. Printed attestation found only from 1951."),
    R("小白菜", urls=["https://en.wikipedia.org/wiki/Cabbage_(folk_song)", "https://zh.wikisource.org/zh-hans/%E5%B0%8F%E7%99%BD%E8%8F%9C"],
      notes="Hebei 小调. Collecting in the Beijing-Hebei area began in the 1920s-30s, and 《河北民歌选集》 appeared in the early 1950s, but a song-specific year was not verified. One recording is 蔡琴's 1981 pop rendition of the same song."),
    R("小看戏", notes="东北 小调/秧歌; " + NO_SRC),
    R("探情郎", notes="东北 小调; " + NO_SRC),
    R("探情郎（天津）", urls=[TJ], notes="Tianjin-flavoured variant; " + NO_SRC),
    R("摇篮曲（东北）", "traditional-adapted", "1960s", "1960", "created by 郑建春 (大连歌舞团) in 1960 from 海城-盖州 area folk tunes; first sung by 徐桂珠",
      "郑建春 (lyrics and arrangement)", "1960",
      ["https://en.wikipedia.org/wiki/Northeastern_Cradle_Song", "https://baike.baidu.com/item/%E4%B8%9C%E5%8C%97%E6%91%87%E7%AF%AE%E6%9B%B2/9105760", "http://www.yueqiziyuan.com/yuepu/2626605403.html"], "medium",
      "'月儿明风儿静'. Usually labelled 东北民歌, but sheet music credits 郑建春 填词编曲 (1960). How much of the melody is folk-derived is unclear."),
    R("放风筝", urls=["https://m.fx361.com/news/2014/0429/23985961.html", "https://m.fx361.com/news/2022/0704/10524781.html"],
      notes="南皮/沧县 小调, described as a variant of the 剪靛花调 tune family, which was popular late Ming-early Qing (family-level, not song-specific); " + NO_SRC),
    R("月牙五更", urls=["https://baike.baidu.com/item/%E6%9C%88%E7%89%99%E4%BA%94%E6%9B%B4/1220202"],
      notes="Liaoning/Jilin 五更体 小调 and 二人转小帽; new lyrics in the 1950s land-reform era as 《翻身五更》; no first-attestation year found."),
    R("梁山伯与祝英台（河北）", urls=["https://zh.wikipedia.org/zh-hans/%E6%A2%81%E5%B1%B1%E4%BC%AF%E8%88%87%E7%A5%9D%E8%8B%B1%E5%8F%B0"],
      notes="Hebei 小调 on the 梁祝 legend (the legend is old; the tune is undated); " + NO_SRC),
    R("沂蒙山小调", "traditional-adapted", "Republican (1912–1949)", "1940", "written June 1940 as 《反对黄沙会》 by 抗大一分校文工团 at 白石屋村, 费县; first sung by 阮若珊 Aug 1940",
      "李林 (music, from local 花鼓调); 阮若珊 (lyrics)", "1940",
      ["https://zh.wikipedia.org/zh-hans/%E6%B2%82%E8%92%99%E5%B1%B1%E5%B0%8F%E8%B0%83", "https://www.chinanews.com/cul/2010/07-23/2420945.shtml", "http://mzt.shandong.gov.cn/art/2021/7/20/art_205229_10289050.html"], "high",
      "A famous 'folk song' that is really a 1940 anti-Japanese propaganda song. The tune was based on a local 花鼓调, and the lyrics were later rewritten into the landscape text known today."),
    R("看秧歌", urls=[ERZHUAN], notes="二人转小帽; " + NO_SRC),
    R("瞧情郎", urls=[ERZHUAN], notes="二人转 piece; " + NO_SRC),
    R("绣荷包（山东）", urls=["https://www.163.com/dy/article/K20RM3P30552N4FE.html"],
      notes="苍山/兰陵 variant of the widespread 绣荷包 tune family (nearly 100 same-title 小调 exist in China); " + NO_SRC),
    R("聊斋俚曲", "traditional-adapted", "Qing (early 18th c.)", NA, "蒲松龄's own 俚曲 texts (4 written before age 60, i.e. before c.1700; 10 written c.1700-1712); exact manuscript years not found",
      "蒲松龄 (texts set to existing 曲牌 such as 迓迓油, 玉娥郎)", "c.1680s-1712",
      ["https://www.ihchina.cn/news_1_details/10949.html", "https://baike.baidu.com/item/%E8%81%8A%E6%96%8B%E4%BF%9A%E6%9B%B2/3517762"], "medium",
      "Genre of 蒲松龄-authored narrative songs on Ming-Qing 俗曲 tunes (calendar years derived from his 1640 birth). Listed as national ICH 2006. The field recording's piece is unspecified."),
    R("茉莉花（东北）", "traditional", "Qing", "1756", MOLIHUA_SRC, urls=MOLIHUA_URLS, conf="medium",
      notes="NE variant sung by an elderly local singer. " + MOLIHUA_NOTE),
    R("荣成渔民号子", urls=["https://wlj.weihai.gov.cn/art/2016/5/17/art_13688_720594.html", "https://www.sohu.com/a/225924999_351132"],
      notes="Provincial ICH (Shandong). 'Thousands of years of fishing history' is a legend-type claim, not evidence. Sources say the genre flourished in the 1950s-70s."),
    R("赶集", urls=[SD], notes="Credited to 山东渤海 region, collected by 渤海区 cultural workers after 1949 (general statement). A separate 胶州 《赶集》 exists; " + NO_SRC),
    R("送情郎", notes="东北 小调; " + NO_SRC),
    R("长腔山歌", urls=[SD], notes="Rare plains 山歌; " + NO_SRC),
]

HUAER_URLS = ["http://www.thepaper.cn/newsDetail_forward_10396125", "http://chinalxnet.com/index/news/detail.html?id=408716"]
HUAER_NOTE = "花儿 as a genre is first documented in 高弘's poem (Ming 成化 era, c.1470s); that is genre-level, not song-level."
TAOMIN = ["https://news.cnr.cn/local/dftj/20240620/t20240620_526755451.shtml"]
TAOMIN_NOTE = "洮岷花儿 (national ICH 2006, UNESCO 2009 as part of 花儿). Claims of Southern-Song origin are unsupported. " + HUAER_NOTE
KAIHUA = ["https://zh.wikipedia.org/zh-hans/%E5%B7%A6%E6%9D%83%E5%BC%80%E8%8A%B1%E8%B0%83", "https://www.ihchina.cn/project_details/28881"]
data["西北部高原"] = [
    R("一对对鸳鸯水上漂", "unknown", comp="disputed: 朱光亮 (神木) or 贺国丰 per different sources",
      urls=["https://baike.baidu.com/item/%E4%B8%80%E5%AF%B9%E5%AF%B9%E9%B8%B3%E9%B8%AF%E6%B0%B4%E4%B8%8A%E6%BC%82/19825214", "https://baike.baidu.com/item/%E4%B8%80%E5%AF%B9%E5%AF%B9%E9%B8%B3%E9%B8%AF%E6%B0%B4%E4%B8%8A%E6%BC%82/20456100"],
      notes="Popularised by the 2015 TV series 平凡的世界. Some sources credit a modern author and others call it a traditional 信天游, so the type is unresolved."),
    R("三十里的明沙二十里的水", notes="山西 河曲-area 山曲; " + NO_SRC),
    R("三十里铺", "traditional-adapted", "Republican (1912–1949)", "1942", "sung/created by 常永昌 in 1942 after 郝增喜's enlistment (story of 郝增喜 and 王凤英, 绥德三十里铺)",
      "常永昌 (folk singer-author, 信天游 tune)", "1942",
      ["https://baike.baidu.com/item/%E4%B8%89%E5%8D%81%E9%87%8C%E9%93%BA/40190", "https://www.sohu.com/a/242605710_366426"], "medium",
      "Treated as traditional-adapted: new words by a known local author on a 信天游 tune. Arranged for unaccompanied choir by 王方亮 in the 1950s. The Mao-meeting anecdote (1943) comes from popular accounts."),
    R("上去高山望平川", "traditional", NA, "1950", "first public performance by 朱仲禄 in 兰州 1950; recorded by China Record Co. after the 1953 national folk music festival",
      urls=["https://baike.baidu.com/item/%E4%B8%8A%E5%8E%BB%E9%AB%98%E5%B1%B1%E6%9C%9B%E5%B9%B3%E5%B7%9D/4378106", "https://www.bilibili.com/video/BV1XA411B7Cc/", "http://paper.people.com.cn/rmrbhwb/html/2016-10/08/content_1717086.htm"], conf="medium",
      notes="河州大令 花儿. " + HUAER_NOTE),
    R("二牡丹令·抓蚂蚱", urls=HUAER_URLS, notes="青海汉族 花儿 (牡丹令). " + HUAER_NOTE),
    R("五哥放羊", urls=["https://m.thepaper.cn/baijiahao_24904586"], notes="河曲 小调, widespread across the NW; " + NO_SRC),
    R("五月花儿", urls=HUAER_URLS, notes="青海汉族 花儿. " + HUAER_NOTE),
    R("交城山", urls=["https://zh.wikipedia.org/zh-hans/%E4%BA%A4%E5%9F%8E%E5%B1%B1", "https://m.163.com/dy/article/FUI1IVP90518FUC3.html"], conf="medium",
      notes="Traditional 山西中部 song. Political rewrite in 1976-78 praising 华国锋 ('游击队…华政委'), reverted after late 1978. The recording is the folk version (not checked against audio). No first attestation found."),
    R("兰花花", "traditional", NA, NA, "collected and arranged by 延安鲁艺 musicians (late 1930s-1940s; exact year not found)",
      urls=["https://zh.wikipedia.org/zh-hans/%E5%85%B0%E8%8A%B1%E8%8A%B1", "http://m.cnwest.com/cyzx/a/2021/09/16/19960055.html"], conf="medium",
      notes="From the 固临 area. Legend: the heroine is 姬延玲 (1919-1942). This is a folk-origin story, not documentary evidence of composition date. 周家洛 is also named as collector/re-creator in some sources."),
    R("十二辰", notes="陕西 小调; " + NO_SRC),
    R("圪梁梁", "newly-composed-folk-style", "1980s", "1981", "written spring 1981 at 保德县文化馆 as 《那是个谁》",
      "杨仲青, 杨仲阔, 周培梧", "1981",
      ["https://www.thepaper.cn/newsDetail_forward_17159522", "https://www.chinawriter.com.cn/n1/2021/1018/c419827-32256792.html"], "high",
      "A 1981 composition often presented as 山西/陕北民歌. Renamed 《圪梁梁》 after 龚琳娜's concert performances."),
    R("大嫂子令", urls=HUAER_URLS, notes="青海 花儿 令. " + HUAER_NOTE),
    R("宁夏花儿", urls=["https://baike.baidu.com/item/%E5%AE%81%E5%A4%8F%E8%8A%B1%E5%84%BF/8496753"], notes="Field recording, song title unspecified. " + HUAER_NOTE),
    R("小小脚儿红绣鞋", notes="陕西 小调; " + NO_SRC),
    R("小桃红", notes="陕北 小调 (小桃红 is also an old 曲牌 name, which is not evidence for this song); " + NO_SRC),
    R("小青马", notes="山西 山曲; " + NO_SRC),
    R("尕妹子弹的是口弦子", "unknown", NA, "2007", "performed by 安宇歌 on CCTV 《民歌·世界》 Spring Festival special, 21 Feb 2007",
      urls=["https://www.ihchina.cn/news_1_details/11455.html"], conf="low",
      notes="Presented as 宁夏花儿 with 回族 口弦. Composer/origin not found; the 2007 date is a broadcast, not an origin."),
    R("巧嘴姑娘", notes="甘肃凉州 小调; " + NO_SRC),
    R("思乡曲", notes="山西 山曲; " + NO_SRC),
    R("想亲亲", urls=["https://m.thepaper.cn/baijiahao_24904586"], notes="河曲 山曲; " + NO_SRC),
    R("打仙桃", notes="陕西 小调; " + NO_SRC),
    R("拜大年（二人台）", urls=["https://www.ihchina.cn/project_details/13329/"], notes="二人台 piece. The 二人台 form is said to have formed c. early 光绪 (genre-level); " + NO_SRC),
    R("月亮偏西了（河州二令）", "traditional", NA, "1953", "tune name 河州二令 coined by 朱仲禄 for the 1953 national folk music festival; recording is by 朱仲禄",
      urls=HUAER_URLS, conf="low", notes="1953 dates the tune's naming, not this text. " + HUAER_NOTE),
    R("桃花红杏花白", "traditional", NA, "1953", "collected by 刘改鱼 from 左权 folk artist 程计年, 1953",
      urls=["https://k.sina.com.cn/article_3167571163_bccd4cdb00101cwxe.html", "https://www.sohu.com/a/717401153_121475763"] + KAIHUA[:1], conf="medium",
      notes="左权开花调. Sources say the 开花调 genre crystallised in the 1930s and was collected from the 1940s. 王志信 later made an art-song arrangement."),
    R("榆林小曲", urls=["https://www.ihchina.cn/art/detail/id/13633.html", "https://baike.baidu.com/item/%E6%A6%86%E6%9E%97%E5%B0%8F%E6%9B%B2/1736717"],
      notes="Field recording, piece unspecified. Legend: brought from Jiangnan by singers of Ming garrison officials (legend, not evidence). National ICH 2006."),
    R("樱桃好吃树难栽", urls=KAIHUA, notes="左权开花调 (genre said to crystallise in the 1930s); " + NO_SRC),
    R("河州大令", "traditional", NA, "1953", "tune name 河州大令 coined by 朱仲禄 for the 1953 national folk music festival",
      urls=HUAER_URLS, conf="low", notes="回族 花儿; the date is for the tune-name, not the text. " + HUAER_NOTE),
    R("泪蛋蛋抛在沙蒿蒿林", urls=["http://jingbianrenda.gov.cn/xxsd/dfctwh/1392038290589855745.html"], notes="陕北 信天游 love song; " + NO_SRC),
    R("爬山调", notes="内蒙古西部 爬山调 genre; " + NO_SRC),
    R("眼泪花儿把心淹了", "traditional", NA, "1938", "notated by 王洛宾 from innkeeper-singer 五朵梅 at 固原 和尚铺, 1938",
      urls=["https://baike.baidu.com/item/%E7%9C%BC%E6%B3%AA%E8%8A%B1%E5%84%BF%E6%8A%8A%E5%BF%83%E6%B7%B9%E4%BA%86/23154157", "http://jlrbszb.dajilin.com/pc/paper/c/202304/16/content_28500.html"], conf="medium",
      notes="宁夏 山花儿. The 王洛宾 transcription anecdote is widely repeated. " + HUAER_NOTE),
    R("羊肚子手巾三道道蓝", urls=["https://baike.baidu.com/item/%E7%BE%8A%E8%82%9A%E5%AD%90%E6%89%8B%E5%B7%BE%E4%B8%89%E9%81%93%E9%81%93%E8%93%9D/12544131"],
      notes="陕北 信天游 text-type. Stage versions (阎维文, 王二妮) may be arranged; " + NO_SRC),
    R("脚夫调", urls=["https://www.qupu123.com/minge/sanzi/p325714.html"], notes="陕北 信天游. Systematic collection began with 鲁艺 in 1938 (general), but no song-specific year was found."),
    R("走三边", "unknown", urls=["http://m.cnwest.com/cyzx/a/2021/09/16/19960055.html", "https://baike.baidu.com/item/%E5%93%A5%E5%93%A5%E5%B8%A6%E6%88%91%E8%B5%B0%E4%B8%89%E8%BE%B9/10594206"],
      notes="Several different songs share this theme: a traditional 走三边 信天游; 孙志宽's version with reform-era lyrics (煤炭石油天然气); and the composed 《哥哥带我走三边》 (党永庵/常宇宏). Which one this 柳强强 recording is has not been determined."),
    R("走西口", "traditional", "late Qing", NA, NA,
      urls=["http://paper.people.com.cn/rmrbhwb/html/2024-10/19/content_26086244.htm", "https://www.sxdaily.com.cn/2019-07/11/content_8004290.html"], conf="low",
      notes="Sources say it was composed in the 咸丰 era (1851-61) by 忻州 people during a drought (太春/玉莲 story, partly legendary), and 二人台 formed c. early 光绪. The recordings include 郭兰英's stage version."),
    R("赶牲灵", "traditional-adapted", NA, "1949", "taught by 张天恩 to 西北文工二团 members (杜锦玉, 白秉权) in 1949; released on record by 中唱 1956",
      "张天恩 (吴堡 folk singer-author)", NA,
      ["https://baike.baidu.com/item/%E8%B5%B6%E7%89%B2%E7%81%B5/9318611", "https://www.ylrb.com/2/2xw/wh/377153.shtml"], "medium",
      "Self-authored 信天游 by 张天恩 from his experience as a muleteer. His year of composition is undated (Baidu lists '1956 张天恩编曲'). Treated as traditional-adapted: known folk author, traditional idiom."),
    R("软三令", urls=HUAER_URLS, notes="甘肃汉族 花儿 令. " + HUAER_NOTE),
    R("镰刀捆的捆捆柴（洮岷花儿）", urls=TAOMIN, notes=TAOMIN_NOTE),
    R("青铜倒了一面锣（洮岷花儿）", urls=TAOMIN, notes=TAOMIN_NOTE),
]

MENGE = ["http://www.chinaquhua.cn/custom/index392.html", "https://www.hanspub.org/journal/paperinformation?paperid=65212"]
MENGE_NOTE = "合肥门歌 (begging door-song tradition). Sources say the genre formed in late Ming and flourished mid-Qing (genre-level); no song-specific date."
YZ = "https://www.sohu.com/a/979399007_121106832"
MJN_URLS = ["https://baike.baidu.com/item/%E5%94%B1%E6%98%A5%E8%B0%83/6383652", "http://paper.people.com.cn/rmrbhwb/html/2016-08/04/content_1701088.htm"]
MJN_NOTE = "孟姜女调/唱春调 family. A 常州 source claims a Ming 正德 (1506-21) origin, and the family was popular as 时调 by mid-Qing; the claim is unverified. No song-specific first attestation."
CHAOHU = ["https://www.ihchina.cn/project_details/12417/"]
data["江淮"] = [
    R("一根丝线牵过河", urls=["https://m.fx361.com/news/2020/1109/7194783.html"], notes="江都 秧田歌/小调; " + NO_SRC),
    R("侉侉调", urls=["https://m.thepaper.cn/newsDetail_forward_30071840"], notes="扬州小调; same tune as 探清水河, and cited as the tune source of 无锡景 (claim); " + NO_SRC),
    R("傻大姐", "unknown", urls=["https://open.spotify.com/track/1q0qX3fStIKF7IwATRZAx5"], notes="Labelled 苏北民歌 (任桂珍). No origin or author information found."),
    R("八段景", urls=[YZ], notes="扬州小调; " + NO_SRC),
    R("凤阳歌", "traditional", "Ming (claimed)", NA, "方中发《湖村口号五首》 (early 康熙, c.1660s; exact year not found)",
      urls=["https://html.rhhz.net/WNSFXYXB/weixin/0f0a99c0-6ac5-435a-a907-b2be85611975.htm", "http://paper.people.com.cn/rmrbhwb/html/2016-07/28/content_1699028.htm"], conf="low",
      notes="Said to originate at Ming 长淮卫 (hence 卫调); the earliest cited mention is early 康熙. The modern text differs from early versions."),
    R("凤阳花鼓", "traditional", "Ming–Qing (genre)", "1767", "《缀白裘》 《花鼓》 scene (edition of 乾隆32 / 1767); 李声振 heard 花鼓 in Beijing in 1756",
      urls=["https://baike.baidu.com/item/%E5%87%A4%E9%98%B3%E8%8A%B1%E9%BC%93/82261", "https://html.rhhz.net/WNSFXYXB/weixin/0f0a99c0-6ac5-435a-a907-b2be85611975.htm", "https://www.gzstv.com/a/b90bfff664614ff4bf6f3238b401d874"], conf="medium",
      notes="The attestation is of the 花鼓 performance genre and its tunes, not the modern '说凤阳道凤阳' text. The recordings include a CCTV stage version, a field recording and an erhu solo."),
    R("十二月景象（合肥门歌）", urls=MENGE, notes=MENGE_NOTE),
    R("南通渔歌", notes="南通 fishermen's song; " + NO_SRC),
    R("堂会祝寿（合肥门歌）", urls=MENGE, notes=MENGE_NOTE),
    R("大麦", urls=[YZ], notes="扬州小调; " + NO_SRC),
    R("太和清音", notes="皖北 narrative singing genre (field recording, piece unspecified). Heritage-listing year not verified; " + NO_SRC),
    R("孟姜女（扬州清曲·十二月调）", urls=MJN_URLS, notes="扬州清曲 version. " + MJN_NOTE),
    R("小小水车八尺长", urls=CHAOHU, notes="巢湖民歌 (national ICH); " + NO_SRC),
    R("打麦号子", notes="南通 work song; " + NO_SRC),
    R("抓壮丁", notes="五河 小调 about conscription. The content suggests Republican-era origin, but no source confirms it, so origin_period is NA."),
    R("拔根芦柴花", "traditional-adapted", NA, "1953", "recorded by 费克 during 江苏省歌舞团 fieldwork in 江都/扬州 (1953; work continued to early 1955)",
      "费克 et al. (江苏省歌舞团 arrangement)", "1953-1955",
      ["http://paper.people.com.cn/rmrbhwb/html/2016-12/08/content_1733960.htm", "http://xinsushang.xhby.net/pc/con/202007/25/content_812359.html"], "medium",
      "Derived from 邵伯栽秧号子. Performed at the July 1956 national folk arts festival (雪飞). The recordings include the tradition-bearer 王瑞如 (号子 form) and 程桂兰's stage version."),
    R("摘石榴", "traditional-adapted", NA, NA, NA, "霍锦堂 (early-1950s 小戏 adaptation); 1979 re-collection/edit by 五河 文化馆 and provincial group",
      "early 1950s; 1979", ["https://baike.baidu.com/item/%E6%91%98%E7%9F%B3%E6%A6%B4/2590252", "https://www.ihchina.cn/project_details/12606/"], "medium",
      "五河民歌 (national ICH 2008; the tradition is said to have flourished in Ming, genre-level). Originated around 小溪镇. The current duet form comes from the 1979 re-edit, popularised in 1982."),
    R("撒趟子撂在外", notes="邵伯秧号子/扬剧小调; " + NO_SRC),
    R("数鸭蛋", urls=[YZ], notes="高邮 小调 (高邮民歌 is national ICH); " + NO_SRC),
    R("春节卖唱歌（合肥门歌）", urls=MENGE, notes=MENGE_NOTE),
    R("春调", urls=MJN_URLS, notes="扬州小调 春调. " + MJN_NOTE),
    R("杨柳青", urls=["https://baike.baidu.com/item/%E6%9D%A8%E6%9F%B3%E9%9D%92/19671785"],
      notes="扬州小调. Popular sources say it dates to the Qing, without documentary citation; " + NO_SRC),
    R("海州五大宫调", "traditional", "Ming (Jiajing era onward, per heritage accounts)", NA, NA,
      urls=["https://www.ihchina.cn/project_details/12532/", "https://culture.gmw.cn/2022-10/27/content_36119423.htm"], conf="low",
      notes="Suite of 5 big 曲牌 (软平, 叠落, 鹂调, 南调, 波扬) linked to the salt trade. National ICH 2006. The origin dating comes from heritage narratives, not a dated document."),
    R("淮北大鼓", urls=["https://www.ihchina.cn/character_detail/8784.html"], notes="Narrative singing. Local accounts put its rudiments in late Ming-early Qing (genre-level, unverified); piece unspecified."),
    R("王三姐赶集", notes="凤阳 小调; " + NO_SRC),
    R("知心客", "traditional", NA, NA, "commercial 78rpm records of 知心客 predating 1937 (gathered by 贺绿汀); year not found",
      urls=["https://baike.baidu.com/item/%E5%A4%A9%E6%B6%AF%E6%AD%8C%E5%A5%B3/9819751", "https://baike.baidu.com/item/%E7%9F%A5%E5%BF%83%E5%AE%A2/56183191"], conf="medium",
      notes="扬州清曲 曲牌 / 苏州 小调. Source tune of 《天涯歌女》 (贺绿汀 arr., 田汉 lyrics, 1937). Legend credits the tune to 江南 '琴王' 张仰求 (unverified)."),
    R("红娘子·拔黄秧（南通山歌）", notes="南通 山歌; " + NO_SRC),
    R("舒城小调", notes="舒城 小调/胡琴书 (field recording); " + NO_SRC),
    R("茉莉花（扬州清曲）", "traditional", "Qing", "1756", MOLIHUA_SRC, urls=MOLIHUA_URLS, conf="medium", notes="扬州清曲 rendition. " + MOLIHUA_NOTE),
    R("送晚茶", urls=CHAOHU, notes="巢湖/无为 民歌 (巢湖民歌 national ICH); " + NO_SRC),
    R("高邮西北乡", urls=[YZ], notes="高邮 小调; adapted in 1986 into the solo song 《我家门前一条河》; " + NO_SRC),
    R("鲜花调·茉莉花（扬州）", "traditional", "Qing", "1756", MOLIHUA_SRC, urls=MOLIHUA_URLS, conf="medium", notes="扬州 鲜花调 variant. " + MOLIHUA_NOTE),
]

JS = ["https://baike.baidu.com/item/%E5%98%89%E5%96%84%E7%94%B0%E6%AD%8C/9634914", "https://www.zjvaa.edu.cn/a/2010310/4538.shtml"]
JS_NOTE = "嘉善田歌 (national ICH 2008). Sources link the genre to Ming 吴歌 as recorded by 冯梦龙's 《山歌》 (genre-level, not song-level); no song-specific date."
ZS = ["https://www.daishan.gov.cn/art/2018/4/11/art_1326439_19381712.html"]
ZS_NOTE = "舟山渔民号子/渔歌 (national ICH); " + NO_SRC
DT = ["https://www.ihchina.cn/project_details/12416/"]
DT_NOTE = "当涂民歌 (national ICH 2006). Six Dynasties/Song literary references are genre-level; " + NO_SRC
data["江浙平原"] = [
    R("四个姑娘去踏车", urls=JS, notes="Named as a representative 嘉善田歌 piece. " + JS_NOTE),
    R("四季棉花", notes="常熟 小调 (historic recording); " + NO_SRC),
    R("四汛渔歌", urls=ZS, notes=ZS_NOTE),
    R("大花名", urls=JS, notes=JS_NOTE),
    R("姐在田里薅豆棵", urls=DT, notes=DT_NOTE),
    R("孟姜女", urls=MJN_URLS, notes="江苏 孟姜女 (十二月花名). " + MJN_NOTE),
    R("宁波小调", urls=["http://ayacd.yrdcpcn.org.cn/_d3/c188/20240911/i186262.phtml"], notes="Field recording; " + NO_SRC),
    R("对鸟", "traditional", NA, "1949", "notated and titled by 乐清中学 music teacher 朱一正 from herd-boys' singing, Feb 1949; an earlier text ('什么飞过青又青') appears in 《瓯海儿歌》 (year not found)",
      urls=["https://baike.baidu.com/item/%E5%AF%B9%E9%B8%9F/7829808", "https://www.thepaper.cn/newsDetail_forward_7636825", "https://news.66wz.com/system/2017/03/28/104978039.shtml"], conf="medium",
      notes="乐清 抛歌 (call-and-response herding song). The 《瓯海儿歌》 text may predate 1949 but its date is not verified."),
    R("徽州民歌", urls=["https://www.ihchina.cn/project_details/12608/"], notes="Field recording, piece unspecified. National ICH 2008; " + NO_SRC),
    R("打水篙号子", urls=ZS, notes=ZS_NOTE),
    R("打莲湘", notes="苏州 打莲湘/打连厢 song-dance (field recording); " + NO_SRC),
    R("打麦歌", urls=DT, notes=DT_NOTE),
    R("摇橹号子", urls=ZS, notes=ZS_NOTE),
    R("新安江号子", notes="黄山/新安江 boatmen's 号子; " + NO_SRC),
    R("无锡景", "traditional", "late Qing–early Republican (sources conflict)", "1921", "Pathé (百代) 78rpm recording, 1921; printed in 《时调大观》 二集 (上海文益书局) 1922",
      urls=["https://www.wuxi.gov.cn/doc/2025/01/04/4470679.shtml", "https://zh.wikipedia.org/zh-cn/%E6%97%A0%E9%94%A1%E6%99%AF", "https://m.thepaper.cn/newsDetail_forward_30071840"], conf="medium",
      notes="Some sources say late-Qing 小调 on the 侉侉调 tune; others date the 无锡景致 text to c.1920 (about 10 years after 1911). A family manuscript (唐建琴) is claimed to be earlier but is undated. 王美玉's 1934 《改良无锡景》 fixed the lyrics."),
    R("杨柳青（苏滩）", notes="苏滩 historic recording (王彩云, 王美云); " + NO_SRC),
    R("桃花妹子", urls=JS, notes="嘉兴 田歌/小调. " + JS_NOTE),
    R("洗菜苔", notes="石台 小调; " + NO_SRC),
    R("玉莲子", urls=DT, notes=DT_NOTE),
    R("秧号子", notes="贵池 秧号子; " + NO_SRC),
    R("紫竹调", urls=["https://baike.baidu.com/item/%E7%B4%AB%E7%AB%B9%E8%B0%83/7361222", "https://baike.weixin.qq.com/v424840.htm"],
      notes="Wu-area 小调 and a basic 沪剧 曲牌 (name from 沪剧 《双脱花》). The claim of a Spring-and-Autumn origin is legend. No dated first attestation found."),
    R("胜浦宣卷", urls=["http://www.artsbuy.com/InfoDetail.aspx?Id=43292"], notes="宣卷 narrative singing (Buddhist-sermon origin; professional performers from Qing, genre-level); piece unspecified."),
    R("舟山海鲜小唱", urls=ZS, notes="舟山 fishermen's 小唱; " + NO_SRC),
    R("芦墟山歌", urls=["https://szfy.wglj.suzhou.com.cn/index.php/gjml/1956", "https://baike.baidu.com/item/%E5%90%B4%E6%AD%8C/3499136"],
      notes="吴歌 (national ICH 2006), known for long narrative 山歌. Ming 冯梦龙 《山歌》 attests 吴歌 as a genre only; piece unspecified."),
    R("苏州好风光", "traditional-adapted", "2000s", "2004", "adapted 2004 as a Suzhou city song from 《大九连环·姑苏风光》",
      "谭亚新 (lyrics); 陈勇 (arrangement)", "2004",
      ["https://zh.wikipedia.org/zh-hans/%E8%8B%8F%E5%B7%9E%E5%A5%BD%E9%A3%8E%E5%85%89", "https://baike.baidu.com/item/%E8%8B%8F%E5%B7%9E%E5%A5%BD%E9%A3%8E%E5%85%89/3854622"], conf="medium",
      notes="A 2004 municipal adaptation of the older 评弹/小调 《大九连环》, first sung by 朱虹. It is often presented as a traditional 苏州民歌."),
    R("茉莉花（江苏）", "traditional-adapted", "Qing", "1756", MOLIHUA_SRC + "; this version collected by 何仿 at 六合/天长 金牛山 in 1942",
      "何仿 (collection 1942; rewrite, unifying the three flowers into 茉莉花)", "1957",
      MOLIHUA_URLS[2:] + ["https://www.hxw.gov.cn/content/2024/01/17/14449772.html", "https://news.sina.com.cn/o/2008-09-22/075814481965s.shtml"], "medium",
      "The canonical modern version was first performed by 前线歌舞团 in 1957. Attribution to 何仿 is disputed (a 2008 article calls the 何仿 credit 'a mistake'). The early dates refer to the 鲜花调 family."),
    R("起篷号子", urls=ZS, notes=ZS_NOTE),
    R("采茶歌", notes="石台 茶歌; " + NO_SRC),
    R("铜陵牛歌", notes="铜陵 cattle songs (field recording). Heritage-listing year not verified; " + NO_SRC),
    R("马灯调", "traditional", "Qing (claimed 道光 era)", NA, NA,
      urls=["https://zh.wikipedia.org/zh-hans/%E9%A9%AC%E7%81%AF%E8%B0%83", "https://baike.baidu.com/item/%E9%A9%AC%E7%81%AF%E8%B0%83/595736"], conf="low",
      notes="宁波/鄞州 跑马灯 song; Wikipedia states a 道光-era origin without a dated document. Municipal ICH."),
    R("黄浦太湖结成亲", "unknown", urls=["https://www.zjvaa.edu.cn/a/2010310/4538.shtml"],
      notes="嘉兴 local-music collection. The title (Huangpu and Taihu 'marrying') may refer to a 20th-century water-works theme, which would make it a newer song, but this is unverified; " + NO_SRC),
]

NANYIN = ["https://zh.wikipedia.org/zh-tw/%E5%8D%97%E7%AE%A1"]
NANYIN_NOTE = "南音/南管 曲. The genre is attested in Ming 万历-era printed anthologies (明刊三种) and was listed as national ICH 2006 and UNESCO 2009. That dates the genre only; Han/Tang-origin claims are legend; no song-specific date."
JINGE = ["https://zh.wikipedia.org/zh-tw/%E9%8C%A6%E6%AD%8C"]
JINGE_NOTE = "漳州锦歌 (歌仔) genre, national ICH 2006; " + NO_SRC
HC = ["https://opinion.udn.com/opinion/story/12369/5907652", "https://hsu-tsang-houei.org/collection/14"]
HC_NOTE = "恒春民谣 tune. 陈达 (1906-81) and other Hengchun singers were recorded in the 1967 民歌采集运动 (许常惠/史惟亮), but no song-specific first attestation was verified."
XUSHI = "https://audio.nmth.gov.tw/audio/zh-TW/Item/Detail/8fd2c66e-494a-4663-9dee-19b84636d56a"
data["闽台"] = [
    R("一只鸟仔哮啾啾", urls=["http://yifertw.blogspot.com/2009/01/blog-post_23.html", "https://zh.wikipedia.org/zh-tw/%E5%91%82%E6%B3%89%E7%94%9F"],
      notes="嘉南 folk song; its origins are disputed. Its link to early Japanese-era events (诸罗山事件) is a popular interpretation, not evidence. 吕泉生 is credited with collecting/arranging it, year not found."),
    R("三千两金（南音）", urls=NANYIN, notes=NANYIN_NOTE),
    R("丢丢铜仔", "traditional-adapted", NA, "1943", "notated by 吕泉生 on 20 Apr 1943 from 宋非我's lyrics; published in 《台湾文艺》 3:3 (1943)",
      "吕泉生 (collection and choral arrangement)", "1943",
      ["https://zh.wikipedia.org/wiki/%E4%B8%9F%E4%B8%9F%E9%8A%85%E4%BB%94", "https://openmuseum.tw/muse/digi_object/a7bdd76a82282bca119bdfeb1f463e7a", "http://jaungyoungming-club.blogspot.com/2016/03/blog-post.html"], conf="high",
      notes="宜兰 folk song. The widely sung version is 吕泉生's 1943 collection, first used in the play 《阉鸡》 and stopped by Japanese police. The recordings (刘福助, 江蕙) are later pop versions."),
    R("五孔小调", urls=HC, notes=HC_NOTE + " The recording is by 陈达."),
    R("五更鼓", "traditional-adapted", NA, "1960", "许石 LP 《台湾乡土民谣全集5》 (大王 KLK-67, 1960-1964; video title says 许石 1962 采编)",
      "许石 (collection/arrangement)", "1960-1964",
      ["https://audio.nmth.gov.tw/audio/%E4%BA%94%E6%9B%B4%E9%BC%93/"], "medium",
      "许石's notes say it was originally a Fujian folk song, later a 嘉南 艺旦 (月旦) song. The LP year is given only as a 1960-64 range."),
    R("六月茉莉", "traditional-adapted", NA, "1962", "许石 LP release (c.1962-1964) labelled '北部民谣'",
      "许石 (transcription/arrangement); 许丙丁 (lyrics)", "1962-1964",
      [XUSHI, "https://audio.nmth.gov.tw/audio/%E5%85%AD%E6%9C%88%E8%8C%89%E8%8E%89/"], "medium",
      "The claim that the melody came from coastal Fujian with Ming-Qing migrants is unsupported. The LP date is given as a range."),
    R("凌波情（锦歌）", urls=JINGE, notes=JINGE_NOTE),
    R("思亲（锦歌）", urls=JINGE, notes=JINGE_NOTE),
    R("出海歌·渔民号子", notes="福建 fishermen's 号子; " + NO_SRC),
    R("十二月景", notes="仙游 (莆仙话) 十二月体 小调; " + NO_SRC),
    R("十二月病囝", notes="福建 月令 pregnancy song (cf. 台湾 病子歌); " + NO_SRC),
    R("卜卦调", "traditional-adapted", NA, "1957", "southern-Taiwan beggar's tune transcribed by 许石, used as dance accompaniment in 1957 under the title 乞食歌",
      "许石 (transcription/arrangement); 许丙丁 (new fortune-telling lyrics)", "1957-1962",
      ["https://audio.nmth.gov.tw/audio/%E5%8D%9C%E5%8D%A6%E8%AA%BF/"], "medium",
      "The 卜卦调 text is 许丙丁's, and its last verse references his own local election campaign. Released on 许石's 《台湾乡土民谣全集3》 (1960-62). Later a Mandarin pop duet (傻瓜与野丫头)."),
    R("古邑山歌", notes="福建 山歌; " + NO_SRC),
    R("台东调", urls=HC, notes=HC_NOTE + " The recording is by 陈达 (台东调 sung with 草蜢仔弄鸡公 text)."),
    R("四季春", urls=HC, notes=HC_NOTE + " The recording is by 陈达."),
    R("四时景（南音）", urls=NANYIN, notes=NANYIN_NOTE),
    R("天乌乌", "traditional-adapted", NA, "1934", "泰平唱片 children's record 《天黑黑／放风吹》, 1934",
      "林福裕 (choral arrangement, 幸福男声合唱团 LP 《台湾民谣集》)", "1965",
      ["https://zh.wikipedia.org/zh-tw/%E5%A4%A9%E7%83%8F%E7%83%8F"], "medium",
      "闽南 nursery song. Most modern renditions derive from 林福裕's 1965 arrangement; it is unverified whether the dataset recordings follow it."),
    R("嫂教姑", notes="潮州歌谣 (Chaoshan); " + NO_SRC),
    R("平埔调", urls=HC, notes=HC_NOTE + " The recording is by 朱丁顺."),
    R("思想起", "traditional", NA, "1967", "recordings of 陈达 in the 1967 民歌采集运动 (许常惠, 史惟亮); an openmuseum item dates a Hengchun recording to Aug 1966",
      urls=HC + ["https://openmuseum.tw/muse/digi_object/fcff8a91168b30460ab531eba82ce000"], conf="medium",
      notes="恒春民谣. The first-recording year conflicts between sources (1966 vs 1967). Popularised nationally via 陈达 and later Mandarin adaptations."),
    R("怨父怨母怨媒人", notes="潮州歌谣; " + NO_SRC),
    R("恒春调", urls=HC, notes=HC_NOTE + " The recording is 刘福助's popular version."),
    R("望春风", "newly-composed-folk-style", "1930s (Japanese-era Taiwan)", "1933", "recorded in Tokyo Aug-Sep 1933 (Columbia), sung by 纯纯; released early 1934",
      "邓雨贤 (music); 李临秋 (lyrics)", "1933",
      ["https://zh.wikipedia.org/zh-tw/%E6%9C%9B%E6%98%A5%E9%A2%A8"], "high",
      "A 1933 popular song, often mislabelled 台湾民谣."),
    R("桃花过渡", "traditional-adapted", NA, "1960", "许石 LP 《台湾乡土民谣全集4》 (大王 KLK-66, 1960-1962)",
      "吕诉上 (lyric revision); 许石 (arrangement)", "1960-1962",
      ["https://audio.nmth.gov.tw/audio/%E6%A1%83%E8%8A%B1%E9%81%8E%E6%B8%A1/", "https://zh.wikipedia.org/zh-tw/%E6%A1%83%E8%8A%B1%E9%81%8E%E6%B8%A1"], "low",
      "车鼓 月令 duet. Origin is disputed: some link it to Chaozhou 《苏六娘》 opera, others note it is absent from the Ming prints; it uses the 灯红歌 tune. Earlier (Japanese-era) recordings likely exist but were not verified, so 1960 is only the earliest verified attestation."),
    R("牛卜吃草（恒春小调）", urls=HC, notes=HC_NOTE + " The recording is by 朱丁顺."),
    R("牛犁歌", "traditional-adapted", NA, "1960", "许石 LP 《台湾乡土民谣全集3》 (大王 KLK-60, 1960-1962)",
      "许石 (arrangement); 许丙丁 (lyrics)", "1960-1962",
      ["https://audio.nmth.gov.tw/audio/%E7%89%9B%E7%8A%81%E6%AD%8C/"], "medium",
      "Farmers' 车鼓-type tune; 许石's arrangement added mambo rhythms. One dataset recording is explicitly the 许石 arrangement (刘福助/朱艳华)."),
    R("病子歌", "traditional", NA, "1960", "许石 LP 《台湾乡土民谣全集5》 (大王 KLK-67, 1960-1964)",
      urls=["https://audio.nmth.gov.tw/audio/%E7%97%85%E5%AD%90%E6%AD%8C/"], conf="low",
      notes="月令 pregnancy duet. The dataset recording is 郑宝珠/李赞声 (铃铃唱片), not 许石's. The LP year is a range, and earlier attestations likely exist but were not found."),
    R("直入花园（南音）", urls=NANYIN, notes=NANYIN_NOTE),
    R("草螟弄鸡公", "traditional-adapted", NA, "1962", "许石 LP (c.1962-1964), southern-Taiwan tune with lyrics revised by 吕诉上",
      "吕诉上 (lyrics); 许石 (arrangement)", "1962-1964",
      ["https://audio.nmth.gov.tw/audio/%E8%8D%89%E8%9E%9F%E4%BB%94%E5%BC%84%E9%9B%9E%E5%85%AC/", "https://zh.wikipedia.org/zh-tw/%E8%8D%89%E8%9E%9F%E5%BC%84%E9%9B%9E%E5%85%AC"], "medium",
      "The dataset recording is 尤雅's 1972 pop version. The 陈达 台东调 recording carries the same text."),
    R("请茶歌（莲花褒歌）", notes="厦门同安 莲花褒歌 (call-and-response tea-picking songs); " + NO_SRC),
    R("锦歌", urls=JINGE, notes="Field recording, piece unspecified. " + JINGE_NOTE),
    R("长工歌（四季春调）", urls=HC, notes=HC_NOTE + " The recording is 朱丁顺's 长工 story text on the 四季春 tune."),
    R("雨夜花", "newly-composed-folk-style", "1930s (Japanese-era Taiwan)", "1933", "melody first published as the children's song 《春天》 (lyrics 廖汉臣, music 邓雨贤), 1933; 雨夜花 recorded by 纯纯 (Columbia), 1934",
      "邓雨贤 (music); 周添旺 (lyrics)", "1934",
      ["https://zh.wikipedia.org/zh-tw/%E9%9B%A8%E5%A4%9C%E8%8A%B1"], "high",
      "A 1934 popular song, often mislabelled 台湾民谣."),
]

for region, rows in data.items():
    with open(os.path.join(OUT, f"{region}.csv"), "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=COLS)
        w.writeheader()
        for r in rows:
            r["region"] = region
            w.writerow(r)
    print(region, len(rows))
